<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="IBM-Testing01" name="com.training.sanity.tests.SatyaLoanTest" tests="6" failures="0" timestamp="18 Feb 2020 15:56:53 GMT" time="0.094" errors="1">
  <testcase name="launch" time="0.094" classname="com.training.sanity.tests.SatyaLoanTest">
    <error type="java.lang.IllegalStateException" message="The driver executable does not exist: E:\Selenium Training\Selenium jar\chromedriver.exe">
      <![CDATA[java.lang.IllegalStateException: The driver executable does not exist: E:\Selenium Training\Selenium jar\chromedriver.exe
at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:146)
at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:141)
at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:159)
at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:94)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
at com.training.sanity.tests.SatyaLoanTest.launch(SatyaLoanTest.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- launch -->
  <testcase name="Account" time="0.000" classname="com.training.sanity.tests.SatyaLoanTest">
    <skipped/>
  </testcase> <!-- Account -->
  <testcase name="Loans" time="0.000" classname="com.training.sanity.tests.SatyaLoanTest">
    <skipped/>
  </testcase> <!-- Loans -->
  <testcase name="View" time="0.000" classname="com.training.sanity.tests.SatyaLoanTest">
    <skipped/>
  </testcase> <!-- View -->
  <testcase name="Amount" time="0.000" classname="com.training.sanity.tests.SatyaLoanTest">
    <skipped/>
  </testcase> <!-- Amount -->
  <testcase name="Repay" time="0.000" classname="com.training.sanity.tests.SatyaLoanTest">
    <skipped/>
  </testcase> <!-- Repay -->
</testsuite> <!-- com.training.sanity.tests.SatyaLoanTest -->
